import keyMirror from 'keymirror';

const ActionTypes = keyMirror({
  // Routes
  REDIRECT: null,

  ERROR_RESPONSE: null,

  LOGIN_REQUEST: null,
  LOGIN_RESPONSE: null,
  LOGIN_RESPONSE_FAILURE: null,
  LOGOUT: null,

  LOAD_BOOKMARKS: null,
  RECEIVE_BOOKMARKS: null,
  RECEIVE_BOOKMARKS_FAILURE: null,

  LOAD_SEARCH_BOOKMARKS: null,
  RECEIVE_SEARCH_BOOKMARKS: null,
  RECEIVE_SEARCH_BOOKMARKS_FAILURE: null,

  LOAD_BOOKMARK: null,
  RECEIVE_BOOKMARK: null,
  RECEIVE_BOOKMARK_FAILURE: null,

  CREATE_BOOKMARK: null,
  RECEIVE_CREATED_BOOKMARK: null,
  RECEIVE_CREATED_BOOKMARK_FAILURE: null,

  REMOVE_BOOKMARK: null,
  RECEIVE_REMOVED_BOOKMARK: null,
  RECEIVE_REMOVED_BOOKMARK_FAILURE: null,

  RECEIVE_BOOKMARK_TAGS: null,
  RECEIVE_BOOKMARK_TAGS_FAILURE: null,

  LOAD_TAGS: null,
  RECEIVE_TAGS: null,
  RECEIVE_TAGS_FAILURE: null,

  RECEIVE_SEARCH_TAGS: null,
  RECEIVE_SEARCH_TAGS_FAILURE: null,

  LOAD_TAG: null,
  RECEIVE_TAG: null,
  RECEIVE_TAG_FAILURE: null,

  CREATE_TAG: null,
  RECEIVE_CREATED_TAG: null,
  RECEIVE_CREATED_TAG_FAILURE: null,

  REMOVE_BOOKMARK_TAGS: null,
  
  RECEIVE_REMOVED_TAG: null,

  EXPORT_DATA: null,
  RECEIVE_EXPORT_DATA: null,

  IMPORT_DATA: null,
  RECEIVE_IMPORT_DATA: null
});

export default ActionTypes;
